[package]
name = "mixer"
version = "0.1.0"
authors = ["Jonas Nick <jonasd.nick@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
rand = "0.6"
